const canvas=document.querySelector('#game-canvas'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),length:document.querySelector('#length'),condition:document.querySelector('#condition'),health:document.querySelector('#health-bar'),overlay:document.querySelector('#overlay'),panel:document.querySelector('.overlay-panel'),introArt:document.querySelector('#intro-art'),introImage:document.querySelector('#intro-image'),lore:document.querySelector('#boss-lore'),art:document.querySelector('#completion-art'),completionImage:document.querySelector('#completion-image'),next:document.querySelector('#next-level-button'),choices:document.querySelector('#snake-choices'),playerEntry:document.querySelector('#player-entry'),playerInput:document.querySelector('#player-name'),playerDisplay:document.querySelector('#player-display'),cleared:document.querySelector('#levels-cleared'),label:document.querySelector('#overlay-label'),title:document.querySelector('#overlay-title'),copy:document.querySelector('#overlay-copy'),start:document.querySelector('#start-button'),pause:document.querySelector('#pause-button'),reset:document.querySelector('#reset-button'),runState:document.querySelector('#run-state'),goal:document.querySelector('#goal-text')};
const COLS=28,ROWS=18,CELL=35,W=COLS*CELL,H=ROWS*CELL,GOALS={1:10,2:15,3:20,4:20,5:11},MOVE_TICKS={python:117,viper:117,boa:117};
const directions={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
const opposite={up:'down',down:'up',left:'right',right:'left'};
const BOSS_CACTI=[{x:14,y:6,scale:1},{x:24,y:4,scale:1.3}];
const skins={python:{top:'#b5dc5b',mid:'#689748',low:'#294b31',joint:'#b1d36b',link:'#6d9a43',shape:'round'},viper:{top:'#e8cf9f',mid:'#b95b34',low:'#482b24',joint:'#f0d7a4',link:'#9f492f',shape:'diamond'},boa:{top:'#dbe9e2',mid:'#759b9a',low:'#344f54',joint:'#dce9de',link:'#6f9591',shape:'armor'}};
const canopyMaps={1:[{x:7.2,y:4.8,r:72,type:'banyan'},{x:19.2,y:10.2,r:86,type:'palm'},{x:25.2,y:4.4,r:66,type:'cedar'},{x:2.1,y:14.8,r:54,type:'fern'}],2:[{x:5.2,y:3.6,r:66,type:'palm'},{x:16.8,y:12.4,r:80,type:'banyan'},{x:25.1,y:6.2,r:70,type:'fern'},{x:9.8,y:15.6,r:58,type:'cedar'}],3:[{x:3.5,y:5.2,r:74,type:'banyan'},{x:13.5,y:2.5,r:66,type:'fern'},{x:23.8,y:12.8,r:88,type:'palm'},{x:8.2,y:15.4,r:62,type:'cedar'},{x:26,y:3,r:54,type:'fern'}],4:[{x:4,y:3,r:68,type:'cedar'},{x:18,y:3.2,r:72,type:'banyan'},{x:25.2,y:9,r:62,type:'fern'},{x:7,y:15,r:78,type:'palm'},{x:20,y:15.5,r:58,type:'cedar'}],5:[{x:3,y:4,r:66,type:'cedar'},{x:8,y:15,r:65,type:'palm'},{x:19,y:14.5,r:76,type:'banyan'},{x:25,y:5,r:60,type:'fern'},{x:2,y:14,r:54,type:'fern'}]};
const puddleMaps={1:[],2:[],3:[
  {x:7,y:4,rx:2.5,ry:1.05,angle:-.22,seed:2,lobes:7,lilies:4,padScale:.85},
  {x:16,y:4,rx:1.25,ry:1.35,angle:.34,seed:5,lobes:5,lilies:0,padScale:1},
  {x:22,y:7,rx:2.15,ry:1.55,angle:-.48,seed:8,lobes:8,lilies:5,padScale:.7},
  {x:5,y:13,rx:1.65,ry:.8,angle:.18,seed:11,lobes:4,lilies:0,padScale:1},
  {x:14,y:14,rx:2.8,ry:1.15,angle:.08,seed:14,lobes:9,lilies:6,padScale:.62},
  {x:23,y:15,rx:1.15,ry:1.1,angle:-.15,seed:17,lobes:6,lilies:2,padScale:1.05}
] ,4:[],5:[{x:4,y:12,rx:1.7,ry:1,angle:.1,seed:21,lobes:6,lilies:3,padScale:.7},{x:23,y:13,rx:2,ry:1.1,angle:-.2,seed:25,lobes:7,lilies:4,padScale:.7}]};
const quicksandMaps={1:[],2:[],3:[],4:[{x:7,y:5,rx:2.2,ry:1.4,angle:.2,seed:4,lobes:7},{x:19,y:5,rx:1.6,ry:2,angle:-.35,seed:9,lobes:6},{x:12,y:12,rx:2.7,ry:1.15,angle:.12,seed:13,lobes:8},{x:23,y:14,rx:1.8,ry:1.2,angle:-.25,seed:18,lobes:5}],5:[{x:7,y:6,rx:2.1,ry:1.2,angle:.18,seed:22,lobes:7},{x:23,y:11,rx:2.4,ry:1.1,angle:-.22,seed:27,lobes:8},{x:11,y:15,rx:1.7,ry:1.25,angle:.3,seed:31,lobes:6}]};
const levelHazards={1:[
  [5,3,'pillar'],[6,3,'pillar'],[13,2,'rock'],[21,3,'thorns'],[22,3,'thorns'],
  [9,7,'wall'],[10,7,'wall'],[11,7,'wall'],[17,6,'pillar'],[23,8,'rock'],
  [4,12,'thorns'],[5,12,'thorns'],[13,12,'wall'],[14,12,'wall'],[20,13,'pillar'],
  [24,14,'rock'],[8,15,'pillar'],[16,15,'thorns']
],2:[[4,3,'wall'],[5,3,'wall'],[10,2,'thorns'],[16,3,'pillar'],[23,3,'rock'],[7,7,'pillar'],[13,6,'wall'],[14,6,'wall'],[20,7,'thorns'],[24,9,'pillar'],[3,12,'rock'],[9,12,'thorns'],[10,12,'thorns'],[16,12,'pillar'],[21,13,'wall'],[22,13,'wall'],[6,15,'pillar'],[13,15,'rock']],3:[[3,2,'pillar'],[4,2,'wall'],[11,3,'rock'],[19,2,'thorns'],[25,4,'pillar'],[9,6,'wall'],[10,6,'wall'],[17,7,'pillar'],[25,9,'rock'],[3,9,'thorns'],[11,10,'pillar'],[18,11,'wall'],[19,11,'wall'],[26,13,'thorns'],[8,15,'rock'],[18,15,'pillar'],[2,16,'wall'],[12,16,'thorns'],[21,16,'rock'],[25,16,'pillar']],4:[[3,3,'wall'],[4,3,'wall'],[11,2,'pillar'],[15,3,'thorns'],[24,3,'rock'],[9,7,'pillar'],[14,7,'wall'],[15,7,'wall'],[22,8,'thorns'],[4,10,'rock'],[17,10,'pillar'],[25,11,'wall'],[6,13,'thorns'],[7,13,'thorns'],[16,14,'rock'],[21,15,'pillar'],[3,16,'pillar'],[26,16,'rock']],5:[[5,3,'rock'],[10,3,'pillar'],[22,3,'wall'],[23,3,'wall'],[3,8,'thorns'],[8,8,'pillar'],[20,8,'rock'],[25,9,'thorns'],[6,14,'wall'],[7,14,'wall'],[14,14,'pillar'],[25,15,'rock']]};
let snake,dir,nextDir,mouse,extraMouse,bossGuard,nextMouseSpawn,relic,resistanceFruit,bossResistance,hazards,canopies,puddles,quicksand,spikes,miceCaught,mouseSpawnIndex,relicsSpawned,state,lastStep,lastWorldStep,flash,particles,mouthUntil,hurtUntil,deathStarted,bossDefeatStarted,quicksandUntil=0,skinName='python',level=1,playerName='',levelsCleared=0,progress={activeName:'',players:{}};

function loadProgress(){try{const saved=JSON.parse(localStorage.getItem('ruinsPythonPlayers'));if(saved&&saved.players)progress=saved}catch(error){}if(progress.activeName){const key=progress.activeName.toLowerCase();if(progress.players[key]){playerName=progress.players[key].name;levelsCleared=progress.players[key].cleared||0;ui.playerInput.value=playerName}}}
function saveProgress(){if(!playerName)return;const key=playerName.toLowerCase();progress.activeName=playerName;progress.players[key]={name:playerName,cleared:levelsCleared};try{localStorage.setItem('ruinsPythonPlayers',JSON.stringify(progress))}catch(error){}}
function registerPlayer(){const name=ui.playerInput.value.trim().replace(/\s+/g,' ');if(!name){ui.playerEntry.classList.add('has-error');ui.playerInput.setAttribute('aria-invalid','true');ui.playerInput.focus();return false}const key=name.toLowerCase(),existing=progress.players[key];playerName=name;levelsCleared=existing?.cleared||0;ui.playerEntry.classList.remove('has-error');ui.playerInput.removeAttribute('aria-invalid');saveProgress();updateHud();return true}

function resetGame(showIntro=true,targetLevel=level){
  level=targetLevel;snake=[{x:5,y:9},{x:4,y:9},{x:3,y:9},{x:2,y:9},{x:1,y:9}];dir='right';nextDir='right';miceCaught=0;mouseSpawnIndex=0;mouse=null;extraMouse=null;nextMouseSpawn=level===5?performance.now()+1800+Math.random()*2200:Infinity;bossGuard=level===5?{x:18,y:8,visible:false,nextAction:performance.now()+4000,hideAt:0,danceAt:0}:null;relic=null;resistanceFruit=null;bossResistance=false;relicsSpawned=0;hazards=levelHazards[level].map(([x,y,type])=>({x,y,type,damaged:false}));canopies=canopyMaps[level];puddles=puddleMaps[level];quicksand=quicksandMaps[level];spikes=[];particles=[];flash=0;mouthUntil=0;hurtUntil=0;deathStarted=0;bossDefeatStarted=0;quicksandUntil=0;lastStep=performance.now();lastWorldStep=lastStep;spawnMouse();state=showIntro?'intro':'ready';setRunState('READY');ui.next.hidden=true;ui.goal.textContent=level===5?'Level 5 / 10 mice + fruit + boss':`Level ${level} / Eat ${GOALS[level]} mice`;const covers={1:'assets/intro-cover-v2.png',2:'assets/level2-cover.png',3:'assets/level3-cover-v2.png',4:'assets/level4-cover-v2.png',5:'assets/level5-cover.png'};ui.introImage.src=covers[level];ui.introImage.alt=level===5?'Three friendly snakes face a boss mouse at a ruined temple':level===4?'Three friendly snakes facing armed spike mice in dry muddy ruins':level===3?'Three friendly snakes with temple, jumping and water mice among lily puddles':level===2?'Striped mice jumping around three friendly snakes in the second ruins':'Three friendly snakes and visible mice in the overgrown ruins';updateHud();
  if(showIntro){if(level===1)showOverlay('EXPEDITION 01','The ruins are infested.','Guide the python through the temple. Eat ten mice. Ruin hazards tear away two body segments.','Enter the ruins');else if(level===2)showOverlay('EXPEDITION 02','Something moved.','Striped ruin mice now hide among the stones. When the python gets close, each has a 50% chance to jump two tiles away.','Hunt the jumpers');else if(level===3)showOverlay('EXPEDITION 03','The courtyard is flooded.','Catch twenty mice across the wet ruins. Water mice may shift between puddles, while temple mice and striped jumpers return.','Enter the wetlands');else if(level===4)showOverlay('EXPEDITION 04','The ground fights back.','Catch twenty normal and spike mice across dry mud and quicksand. Spike mice fire one shot up to three tiles; bite after they fire to avoid damage.','Enter the badlands');else showOverlay('EXPEDITION 05','The keeper of the temple.','Catch ten mixed mice. Then collect the resistance fruit that rises from the water before confronting the keeper. It fires steady aimed shots and may jump away.','Face the keeper')}else{ui.panel.classList.remove('has-art');ui.art.hidden=true;ui.overlay.hidden=true}
}
function solidAt(x,y){return level===5&&x>=17&&x<=19&&y>=4&&y<=6}
function occupied(x,y){return solidAt(x,y)||snake.some(s=>s.x===x&&s.y===y)||hazards.some(h=>h.x===x&&h.y===y)||(mouse&&mouse.x===x&&mouse.y===y)||(extraMouse&&extraMouse.x===x&&extraMouse.y===y)||(relic&&relic.x===x&&relic.y===y)||(resistanceFruit&&resistanceFruit.x===x&&resistanceFruit.y===y)}
function emptyCell(){let cell;do{cell={x:1+Math.floor(Math.random()*(COLS-2)),y:1+Math.floor(Math.random()*(ROWS-2))}}while(occupied(cell.x,cell.y));return cell}
function inPuddleCell(cell){return puddles.some(p=>{const dx=cell.x-p.x,dy=cell.y-p.y,c=Math.cos(-p.angle),s=Math.sin(-p.angle),rx=dx*c-dy*s,ry=dx*s+dy*c;return rx*rx/(p.rx*p.rx)+ry*ry/(p.ry*p.ry)<.72})}
function makeMouse(type,cell=null){if(!cell){if(type==='water'){const available=puddles.filter(p=>!occupied(p.x,p.y));cell=available.length?available[Math.floor(Math.random()*available.length)]:emptyCell()}else{do{cell=emptyCell()}while(level===5&&inPuddleCell(cell))}}return{...cell,type,tested:false,jump:0,armed:type==='spike',fired:false,lastShot:0,lastJump:0}}
function spawnMouse(){if(level===5){if(miceCaught>=10){extraMouse=null;mouse=makeMouse('boss',{x:18,y:8});const waters=puddles.filter(p=>!occupied(p.x,p.y));resistanceFruit=waters.length?{x:waters[0].x,y:waters[0].y,riseAt:performance.now()}:emptyCell();if(bossGuard){bossGuard.visible=false;bossGuard.nextAction=Infinity}return}const type=['normal','jumper','water','spike'][mouseSpawnIndex%4];mouseSpawnIndex++;const created=makeMouse(type);if(!mouse)mouse=created;else if(!extraMouse)extraMouse=created;return}const type=level===1?'normal':level===2?'jumper':level===3?['normal','jumper','water'][mouseSpawnIndex%3]:['normal','spike'][mouseSpawnIndex%2];mouseSpawnIndex++;mouse=makeMouse(type)}
function updateLevel5MouseSpawn(){if(level!==5||miceCaught>=10||extraMouse||performance.now()<nextMouseSpawn)return;spawnMouse();nextMouseSpawn=Infinity}
function spawnRelic(){if(!relic&&relicsSpawned<2){relic=emptyCell();relicsSpawned++}}
function updateHud(){
  ui.score.textContent=miceCaught;document.querySelector('#mouse-goal').textContent=GOALS[level];ui.length.textContent=snake.length;ui.playerDisplay.textContent=playerName||'Not signed in';ui.cleared.textContent=levelsCleared;
  document.querySelectorAll('[data-replay-level]').forEach(button=>{const target=Number(button.dataset.replayLevel);button.disabled=target>1&&levelsCleared<target-1;button.classList.toggle('is-current',target===level)});
  const ratio=Math.min(1,(snake.length-2)/7);ui.health.style.width=`${Math.max(8,ratio*100)}%`;
  if(snake.length>=7){ui.condition.textContent='Thriving';ui.condition.style.color='#9bc34a';ui.health.style.background='#9bc34a'}
  else if(snake.length>=5){ui.condition.textContent='Healthy';ui.condition.style.color='#9bc34a';ui.health.style.background='#9bc34a'}
  else{ui.condition.textContent='Critical';ui.condition.style.color='#d26343';ui.health.style.background='#d26343'}
}
function setRunState(label){ui.runState.textContent=label;document.documentElement.dataset.gameState=label.toLowerCase()}
function showOverlay(label,title,copy,button){const complete=state==='levelComplete'||state==='won',intro=state==='intro';ui.label.textContent=label;ui.title.textContent=title;ui.copy.textContent=copy;ui.start.textContent=button;ui.start.hidden=state==='levelComplete';ui.choices.hidden=state==='paused'||complete;ui.playerEntry.hidden=complete||state==='paused'||level>1;ui.introArt.hidden=!intro;ui.lore.hidden=!(intro&&level===5);ui.art.hidden=!complete;ui.panel.classList.toggle('has-art',complete);ui.panel.classList.toggle('has-intro',intro);ui.overlay.hidden=false;requestAnimationFrame(()=>{ui.overlay.scrollTop=0})}
function startGame(){if(state==='levelComplete'){resetGame(true,level+1);return}else if(state==='won'){resetGame(true,1);return}else if(state==='lost')resetGame(false,level);if(state==='intro'&&level===1&&!registerPlayer())return;if(state==='intro'||state==='ready'||state==='paused'){state='running';lastStep=performance.now();lastWorldStep=lastStep;ui.overlay.hidden=true;ui.pause.textContent='II';ui.pause.setAttribute('aria-label','Pause game');setRunState('RUNNING')}}
function pauseGame(){if(state==='running'){state='paused';setRunState('PAUSED');showOverlay('EXPEDITION PAUSED','The python is resting.','The ruins will wait. Continue when you are ready.','Continue');ui.pause.textContent='\u25b6';ui.pause.setAttribute('aria-label','Resume game')}else if(state==='paused')startGame()}
function setDirection(name){if(state==='intro'||state==='ready'){if(state==='intro'&&level===1&&!registerPlayer())return;dir=name;nextDir=name;state='running';lastStep=performance.now();ui.overlay.hidden=true;setRunState('RUNNING');return}if(state!=='running'||opposite[dir]===name)return;nextDir=name}
function burst(x,y,color,count=10){for(let i=0;i<count;i++)particles.push({x:(x+.5)*CELL,y:(y+.5)*CELL,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:.35+Math.random()*.4,color})}
function lose(reason){if(state==='dying'||state==='lost')return;state='dying';deathStarted=performance.now();setRunState('FAILED');setTimeout(()=>{if(state!=='dying')return;state='lost';showOverlay('EXPEDITION FAILED','Lost to the ruins.',reason,'Try again')},900)}
function win(){state=level<5?'levelComplete':'won';levelsCleared=Math.max(levelsCleared,level);saveProgress();updateHud();setRunState('CLEARED');burst(snake[0].x,snake[0].y,'#e0af43',35);ui.completionImage.src=level===5?'assets/final-temple-cover.png':'assets/level-complete-cover.png';ui.completionImage.alt=level===5?'Three happy snakes face the camera at the clean temple with different mouse tails hanging from their mouths':'Happy snake smiling in the reclaimed ruins with a mouse tail at its mouth';const titles={1:'The first nest is cleared.',2:'The jumpers are caught.',3:'The flooded courtyard is reclaimed.',4:'The badlands are quiet.',5:'The temple is clean again.'},copies={1:`${playerName} has eaten ten mice. Movement stirs deeper in the ruins.`,2:`${playerName} caught all fifteen jumping mice. Water glints beyond the next arch.`,3:`${playerName} caught all twenty mice across the flooded courtyard. Dry ground waits ahead.`,4:`${playerName} caught all twenty normal and spike mice. A hidden temple opens.`,5:`${playerName} found the water fruit, defeated the keeper, and reclaimed the temple.`};showOverlay(level<5?`LEVEL ${level} CLEARED`:'TEMPLE CLEARED',titles[level],copies[level],level<5?`Go to level ${level+1}`:'Play again');if(level<5){ui.next.innerHTML=`Go to level ${level+1} <span aria-hidden="true">&#8594;</span>`;ui.next.hidden=false}else ui.next.hidden=true}
function maybeJumpMouse(approachingHead,target=mouse){
  if(!target||target.type==='normal'||target.type==='spike'||target.type==='boss'||target.tested||Math.abs(approachingHead.x-target.x)+Math.abs(approachingHead.y-target.y)>3)return;
  target.tested=true;if(Math.random()>=.5)return;
  const jumps=target.type==='water'?puddles.filter(p=>(p.x!==target.x||p.y!==target.y)&&!occupied(p.x,p.y)).map(p=>({x:p.x,y:p.y})):[[2,0],[-2,0],[0,2],[0,-2],[2,2],[-2,-2]].map(([dx,dy])=>({x:target.x+dx,y:target.y+dy})).filter(cell=>cell.x>0&&cell.x<COLS-1&&cell.y>0&&cell.y<ROWS-1&&!occupied(cell.x,cell.y)&&(cell.x!==approachingHead.x||cell.y!==approachingHead.y));
  if(!jumps.length)return;const landing=jumps[Math.floor(Math.random()*jumps.length)];target.x=landing.x;target.y=landing.y;target.jump=1;burst(target.x,target.y,target.type==='water'?'#62bac0':'#8fb1ad',10);
}
function aimedVector(from,to){const dx=to.x-from.x,dy=to.y-from.y,length=Math.hypot(dx,dy)||1;return{x:dx/length,y:dy/length}}
function updateBoss(approachingHead){if(mouse.type!=='boss')return;const dx=approachingHead.x-mouse.x,dy=approachingHead.y-mouse.y,distance=Math.abs(dx)+Math.abs(dy),now=performance.now();if(distance<=8&&now-mouse.lastShot>1800){const shot=aimedVector(mouse,approachingHead);spikes.push({x:mouse.x,y:mouse.y,dx:shot.x,dy:shot.y,lane:0,life:14,kind:'spit'});mouse.lastShot=now;burst(mouse.x,mouse.y,'#6da43d',12)}if(distance>0&&distance<=4&&now-mouse.lastJump>1500&&Math.random()<.28){const hides=[{x:16,y:5},{x:20,y:5},{x:16,y:8},{x:20,y:8},{x:13,y:6},{x:22,y:6}].filter(p=>!occupied(p.x,p.y)&&(p.x!==approachingHead.x||p.y!==approachingHead.y));if(hides.length){const next=hides[Math.floor(Math.random()*hides.length)];mouse.x=next.x;mouse.y=next.y;mouse.jump=1;mouse.lastJump=now;burst(mouse.x,mouse.y,'#7fa64b',15)}}}
function updateBossGuard(){if(level!==5||!bossGuard||miceCaught>=10)return;const now=performance.now(),distance=Math.abs(snake[0].x-bossGuard.x)+Math.abs(snake[0].y-bossGuard.y);if(bossGuard.visible){if(distance<5){bossGuard.visible=false;bossGuard.nextAction=now+4200;spikes=spikes.filter(spike=>spike.kind!=='bossSpit');return}if(now>=bossGuard.hideAt){bossGuard.visible=false;bossGuard.nextAction=now+5200+Math.random()*4200}return}if(now<bossGuard.nextAction)return;if(distance<7){bossGuard.nextAction=now+1800;return}bossGuard.visible=true;bossGuard.danceAt=now+420;bossGuard.hideAt=now+2100;const shot=aimedVector(bossGuard,snake[0]);spikes.push({x:bossGuard.x,y:bossGuard.y,dx:shot.x,dy:shot.y,lane:0,life:13,kind:'bossSpit'});burst(bossGuard.x,bossGuard.y,'#8bd24e',18)}
function damageSnake(x,y,reason,amount=2){flash=1;hurtUntil=performance.now()+430;burst(x,y,'#b54f35',16);snake.splice(Math.max(2,snake.length-amount),amount);updateHud();if(snake.length<=2){lose(reason);return true}return false}
function fireSpikeMouse(approachingHead,target=mouse){if(!target||target.type!=='spike'||!target.armed)return;const dx=approachingHead.x-target.x,dy=approachingHead.y-target.y,distance=Math.abs(dx)+Math.abs(dy);if(distance===0||distance>3)return;const shot=Math.abs(dx)>=Math.abs(dy)?{x:Math.sign(dx)||1,y:0}:{x:0,y:Math.sign(dy)||1};target.armed=false;target.fired=true;target.fireAt=performance.now();spikes.push({x:target.x,y:target.y,dx:shot.x,dy:shot.y,lane:0,life:4});burst(target.x,target.y,'#e9ddbd',14)}
function updateSpikes(){const survivors=[];for(const spike of spikes){spike.x+=spike.dx;spike.y+=spike.dy;spike.life--;const sideX=-spike.dy*spike.lane,sideY=spike.dx*spike.lane,sx=Math.round(spike.x+sideX),sy=Math.round(spike.y+sideY);if(sx<0||sx>=COLS||sy<0||sy>=ROWS||spike.life<=0||solidAt(sx,sy)||hazards.some(h=>h.x===sx&&h.y===sy))continue;if(snake.some(s=>s.x===sx&&s.y===sy)){if(damageSnake(sx,sy,spike.kind==='spit'||spike.kind==='bossSpit'?'The temple keeper\'s venom ended the expedition.':'The spike mice overwhelmed the python.'))return;continue}survivors.push(spike)}spikes=survivors}
function inQuicksand(cell){return quicksand.some(p=>{const dx=cell.x-p.x,dy=cell.y-p.y,c=Math.cos(-p.angle),s=Math.sin(-p.angle),rx=dx*c-dy*s,ry=dx*s+dy*c;return rx*rx/(p.rx*p.rx)+ry*ry/(p.ry*p.ry)<.72})}
function step(){
  dir=nextDir;const head={x:snake[0].x+directions[dir].x,y:snake[0].y+directions[dir].y};
  if(head.x<0||head.x>=COLS||head.y<0||head.y>=ROWS){lose('The python slipped beyond the ruined temple walls.');return}
  if(snake.some((s,i)=>i>0&&s.x===head.x&&s.y===head.y)){lose('The python crossed its own trail.');return}
  if(solidAt(head.x,head.y)){damageSnake(head.x,head.y,'The keeper shrine proved immovable.');return}
  if(level===5&&BOSS_CACTI.some(cactus=>head.x===cactus.x&&head.y===cactus.y)){if(damageSnake(head.x,head.y,'The keeper cactus scratched the python.',1))return}
  if((level===4||level===5)&&inQuicksand(head))quicksandUntil=performance.now()+3000;
  const hazardIndex=hazards.findIndex(h=>h.x===head.x&&h.y===head.y);
  if(hazardIndex>=0){
    const hazard=hazards[hazardIndex];hazards.splice(hazardIndex,1);flash=1;burst(head.x,head.y,hazard.type==='thorns'?'#a34d32':'#899084',14);
    damageSnake(head.x,head.y,'Too many impacts stripped away the python\'s body.');
    return;
  }
  maybeJumpMouse(head);maybeJumpMouse(head,extraMouse);fireSpikeMouse(head);fireSpikeMouse(head,extraMouse);snake.unshift(head);
  if(resistanceFruit&&head.x===resistanceFruit.x&&head.y===resistanceFruit.y){bossResistance=true;resistanceFruit=null;mouthUntil=performance.now()+420;burst(head.x,head.y,'#8ee4d7',24);const tail=snake[snake.length-1];snake.push({...tail});updateHud()}
  const eaten=head.x===mouse.x&&head.y===mouse.y?mouse:extraMouse&&head.x===extraMouse.x&&head.y===extraMouse.y?extraMouse:null;
  if(eaten&&eaten.type==='boss'&&!bossResistance){eaten.jump=1;eaten.lastJump=performance.now();const escapes=[{x:16,y:5},{x:20,y:5},{x:16,y:8},{x:20,y:8},{x:13,y:6},{x:22,y:6}].filter(p=>!occupied(p.x,p.y));if(escapes.length)Object.assign(eaten,escapes[Math.floor(Math.random()*escapes.length)]);burst(head.x,head.y,'#78c9bd',16);snake.pop();return}
  if(eaten&&eaten.type==='boss'){mouthUntil=performance.now()+650;bossDefeatStarted=performance.now();state='bossDefeated';spikes=[];setRunState('KEEPER DEFEATED');burst(head.x,head.y,'#f1d36b',36);setTimeout(()=>{if(state!=='bossDefeated')return;miceCaught++;mouse=null;updateHud();win()},1900);return}
  if(eaten){const armedBite=eaten.type==='spike'&&eaten.armed;mouthUntil=performance.now()+280;miceCaught++;burst(head.x,head.y,armedBite?'#d69a50':'#d9c9b8',12);if(armedBite&&damageSnake(head.x,head.y,'An armed spike mouse proved too dangerous.'))return;if(level===5){if(eaten===mouse){mouse=extraMouse;extraMouse=null}else extraMouse=null;if(miceCaught>=10)spawnMouse();else{if(!mouse)spawnMouse();nextMouseSpawn=performance.now()+1300+Math.random()*2500}}else spawnMouse();if(miceCaught===3||miceCaught===7)spawnRelic();updateHud();if(miceCaught>=GOALS[level]){win();return}}
  else if(relic&&head.x===relic.x&&head.y===relic.y){const tail=snake[snake.length-1];snake.push({...tail},{...tail});burst(head.x,head.y,'#e0af43',18);relic=null;updateHud()}
  else snake.pop();
}

const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};
window.addEventListener('keydown',event=>{if(keyMap[event.key]){event.preventDefault();setDirection(keyMap[event.key])}else if(event.code==='Space'){event.preventDefault();pauseGame()}else if(event.key.toLowerCase()==='r')resetGame(false)});
document.querySelectorAll('[data-direction]').forEach(button=>button.addEventListener('pointerdown',()=>setDirection(button.dataset.direction)));
let swipeStart=null;canvas.addEventListener('pointerdown',e=>{swipeStart={x:e.clientX,y:e.clientY}});canvas.addEventListener('pointerup',e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;if(Math.hypot(dx,dy)<18)return;setDirection(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))});
ui.start.addEventListener('click',startGame);ui.pause.addEventListener('click',pauseGame);ui.reset.addEventListener('click',()=>resetGame(false));
ui.next.addEventListener('click',()=>resetGame(true,Math.min(5,level+1)));
ui.playerInput.addEventListener('input',()=>{ui.playerEntry.classList.remove('has-error');ui.playerInput.removeAttribute('aria-invalid')});ui.playerInput.addEventListener('keydown',event=>{if(event.key==='Enter')startGame()});
function chooseSkin(name){if(!skins[name])return;skinName=name;document.querySelectorAll('.snake-choice').forEach(choice=>choice.classList.toggle('is-selected',choice.dataset.skin===name))}
document.querySelectorAll('.snake-choice').forEach(button=>button.addEventListener('click',()=>chooseSkin(button.dataset.skin)));
document.querySelectorAll('[data-replay-level]').forEach(button=>button.addEventListener('click',()=>{const target=Number(button.dataset.replayLevel);if(target===1||levelsCleared>=target-1)resetGame(true,target)}));

function tileNoise(x,y){return((x*91+y*47+x*y*13)%100)/100}
function drawFloor(){
  ctx.fillStyle=level===5?'#344139':level===4?'#51483a':level===2?'#283432':'#263229';ctx.fillRect(0,0,W,H);
  for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){
    const n=tileNoise(x+level*2,y),px=x*CELL,py=y*CELL;ctx.fillStyle=level===5?(n>.72?'#4f5c4f':n<.18?'#303d35':'#424f45'):level===4?(n>.72?'#74634b':n<.18?'#3e3b31':'#5c5141'):level===2?(n>.72?'#3c4843':n<.18?'#293834':'#34413c'):(n>.72?'#364338':n<.18?'#2b362e':'#313d34');ctx.fillRect(px+1,py+1,CELL-2,CELL-2);
    ctx.strokeStyle='rgba(8,14,10,.26)';ctx.strokeRect(px+.5,py+.5,CELL-1,CELL-1);
    if(n>.8){ctx.strokeStyle='#66705f';ctx.beginPath();ctx.moveTo(px+4,py+8);ctx.lineTo(px+17,py+17);ctx.lineTo(px+12,py+31);ctx.stroke()}
    if(n<.15&&level!==4){ctx.strokeStyle='#55744c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px+6,py+CELL);ctx.quadraticCurveTo(px+7,py+18,px+15,py+12);ctx.moveTo(px+20,py+CELL);ctx.quadraticCurveTo(px+22,py+22,px+29,py+17);ctx.stroke();ctx.lineWidth=1}
    if(level===4&&n>.62){ctx.strokeStyle='rgba(44,37,28,.62)';ctx.beginPath();ctx.moveTo(px+5,py+8);ctx.lineTo(px+14,py+13);ctx.lineTo(px+9,py+22);ctx.moveTo(px+14,py+13);ctx.lineTo(px+25,py+9);ctx.moveTo(px+9,py+22);ctx.lineTo(px+20,py+29);ctx.stroke()}
  }
  if(level===5){ctx.strokeStyle='rgba(12,22,16,.45)';ctx.lineWidth=3;for(let x=0;x<=W;x+=CELL*2){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<=H;y+=CELL*2){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
  ctx.fillStyle='rgba(9,14,11,.28)';ctx.fillRect(0,0,W,14);ctx.fillRect(0,H-14,W,14);ctx.fillRect(0,0,14,H);ctx.fillRect(W-14,0,14,H);
  for(let i=0;i<72;i++){const edge=i%4,pos=tileNoise(i,edge)*((edge<2?W:H)-20)+10,x=edge===0?pos:edge===1?pos:edge===2?8+tileNoise(i,9)*14:W-8-tileNoise(i,9)*14,y=edge===0?8+tileNoise(i,7)*14:edge===1?H-8-tileNoise(i,7)*14:pos,r=5+tileNoise(i,4)*10;ctx.fillStyle=i%3?'#38563a':'#527044';ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();if(i%5===0){ctx.strokeStyle='#75915b';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(i%2?8:-8),y-15);ctx.stroke()}}
  const cornerSets={1:[[22,24],[W-22,24],[22,H-24],[W-22,H-24]],2:[[48,18],[W-25,62],[18,H-72],[W-74,H-20],[W*.62,15]],3:[[18,82],[W-90,18],[70,H-18],[W-20,H-105],[W*.45,H-14],[W-14,H*.42]],4:[[26,30],[W-38,25],[30,H-38],[W-30,H-60],[W*.55,18]],5:[[25,45],[W-35,45],[42,H-35],[W-42,H-42],[W*.48,H-20],[W-18,H*.5]]},corners=cornerSets[level];corners.forEach(([x,y],corner)=>{for(let i=0;i<(level===1?11:level===2?14:16);i++){const a=(corner*Math.PI/2)+i*.56+level*.23,r=18+(i%4)*8,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;ctx.strokeStyle=i%2?(level===4?'#68704a':level===3?'#528477':level===2?'#557d68':'#6d8c55'):'#416d46';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo((x+px)/2+(i%2?8:-8),(y+py)/2,px,py);ctx.stroke();ctx.fillStyle=i%3?(level===4?'#78805a':level===3?'#5b8b76':level===2?'#4d7663':'#547c4d'):'#78915b';ctx.beginPath();ctx.ellipse(px,py,9+(level>1?2:0),4,a,0,7);ctx.fill()}for(let m=0;m<4;m++){ctx.fillStyle=level===5?['#e05f79','#a970cf','#f0b84c','#76b8d0'][m]:level===3&&m%2?'#9e76a8':m%2?'#b6a15e':'#8f543a';ctx.beginPath();ctx.arc(x-12+m*9,y+10+(m%2)*5,level===5?7+m%2:3+m%2,0,7);ctx.fill();if(level===5){ctx.fillStyle='#f4df8a';ctx.beginPath();ctx.arc(x-12+m*9,y+10+(m%2)*5,2.5,0,7);ctx.fill()}}})
}
function drawTemple(){if(level!==5)return;const x=17*CELL,y=4*CELL,w=3*CELL,h=3*CELL;ctx.save();ctx.fillStyle='rgba(8,14,10,.45)';ctx.fillRect(x+10,y+14,w,h+18);ctx.fillStyle='#697268';ctx.strokeStyle='#27332c';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+8,y+h);ctx.lineTo(x,y+24);ctx.lineTo(x+18,y);ctx.lineTo(x+w-12,y+3);ctx.lineTo(x+w,y+27);ctx.lineTo(x+w-7,y+h);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#929b86';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+w/2,y+58,25,Math.PI,0);ctx.lineTo(x+w/2+25,y+h);ctx.lineTo(x+w/2-25,y+h);ctx.closePath();ctx.stroke();ctx.fillStyle='#111b15';ctx.fill();ctx.strokeStyle='#3e4b41';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+17,y+20);ctx.lineTo(x+34,y+39);ctx.lineTo(x+22,y+63);ctx.moveTo(x+w-18,y+15);ctx.lineTo(x+w-37,y+38);ctx.lineTo(x+w-24,y+69);ctx.stroke();ctx.fillStyle='#526b48';ctx.beginPath();ctx.arc(x+w/2,y+29,15,0,7);ctx.fill();ctx.fillStyle='#18231b';ctx.beginPath();ctx.arc(x+w/2,y+29,8,0,7);ctx.fill();ctx.restore()}
function drawBossCactus(){if(level!==5)return;BOSS_CACTI.forEach(cactus=>{const x=(cactus.x+.5)*CELL,y=(cactus.y+.5)*CELL;ctx.save();ctx.translate(x,y);ctx.scale(cactus.scale,cactus.scale);ctx.shadowColor='rgba(8,20,12,.45)';ctx.shadowBlur=8;ctx.strokeStyle='#183923';ctx.lineWidth=2;const pads=[{x:0,y:3,rx:12,ry:27,a:0},{x:-14,y:7,rx:9,ry:18,a:-.65},{x:14,y:12,rx:8,ry:17,a:.7},{x:-23,y:18,rx:8,ry:13,a:-.9}];pads.forEach((p,i)=>{ctx.fillStyle=i%2?'#367441':'#245c35';ctx.beginPath();ctx.ellipse(p.x,p.y,p.rx,p.ry,p.a,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#d7db9b';for(let s=0;s<5;s++){const a=s*2.3+i;ctx.beginPath();ctx.moveTo(p.x+Math.cos(a)*p.rx*.55,p.y+Math.sin(a)*p.ry*.55);ctx.lineTo(p.x+Math.cos(a)*p.rx*.75+Math.cos(a)*6,p.y+Math.sin(a)*p.ry*.75+Math.sin(a)*6);ctx.lineTo(p.x+Math.cos(a+.35)*p.rx*.6,p.y+Math.sin(a+.35)*p.ry*.6);ctx.closePath();ctx.fill()}});ctx.fillStyle='#9d2638';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(-12+i*12,-12+(i%2)*8,6,8,i*.4,0,7);ctx.fill();ctx.fillStyle='#57a83e';ctx.fillRect(-14+i*12,-21+(i%2)*8,4,5);ctx.fillStyle='#9d2638'}const fx=12,fy=-7;ctx.fillStyle='#d84b54';for(let i=0;i<7;i++){const a=i*Math.PI*2/7;ctx.beginPath();ctx.ellipse(fx+Math.cos(a)*7,fy+Math.sin(a)*7,7,3,a,0,7);ctx.fill()}ctx.fillStyle='#b8e45d';ctx.beginPath();ctx.arc(fx,fy,3,0,7);ctx.fill();ctx.restore()})}
function drawBossGuard(){if(!bossGuard||!bossGuard.visible||miceCaught>=10)return;const now=performance.now(),dancing=now>=bossGuard.danceAt,baseX=(bossGuard.x+.5)*CELL,baseY=(bossGuard.y+.5)*CELL,x=baseX+(dancing?Math.sin(now/95)*8:0),y=baseY+(dancing?Math.abs(Math.sin(now/130))*-5:0),tilt=dancing?Math.sin(now/110)*.16:0;ctx.save();ctx.translate(x,y);ctx.rotate(tilt);drawBossFigure(0,0,.95);ctx.restore()}
function drawBossFigure(x,y,scale=1){const pulse=1+Math.sin(performance.now()/120)*.035;ctx.save();ctx.translate(x,y);ctx.scale(scale*pulse,scale*pulse);ctx.shadowColor='rgba(85,8,17,.6)';ctx.shadowBlur=12;ctx.fillStyle='#101614';ctx.strokeStyle='#050908';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(-5,3,28,19,-.08,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#17452c';ctx.beginPath();ctx.arc(17,-5,16,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#6f202a';ctx.beginPath();ctx.arc(8,-17,8,0,7);ctx.arc(23,-18,9,0,7);ctx.fill();ctx.fillStyle='#2d9149';for(let i=0;i<7;i++){ctx.save();ctx.rotate(-1.28+i*.25);ctx.beginPath();ctx.ellipse(4,-19,14,4,0,0,7);ctx.fill();ctx.restore()}ctx.fillStyle='#a92b35';ctx.strokeStyle='#e0524e';ctx.beginPath();ctx.moveTo(8,-19);ctx.lineTo(17,-31);ctx.lineTo(27,-19);ctx.lineTo(23,-9);ctx.lineTo(12,-10);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#09100d';ctx.strokeStyle='#35a65a';for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(-20+i*11,-9);ctx.lineTo(-11+i*11,8);ctx.lineTo(-24+i*11,9);ctx.closePath();ctx.fill();ctx.stroke()}ctx.shadowBlur=8;ctx.shadowColor='#9bf05c';ctx.fillStyle='#c4ff75';ctx.beginPath();ctx.arc(13,-8,3,0,7);ctx.fill();ctx.shadowColor='#e84343';ctx.fillStyle='#ff5a4d';ctx.beginPath();ctx.arc(23,-8,3,0,7);ctx.fill();ctx.shadowColor='#79df4b';ctx.fillStyle='rgba(82,191,58,.8)';ctx.beginPath();ctx.arc(7,0,5,0,7);ctx.arc(27,0,5,0,7);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#101614';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-28,6);ctx.quadraticCurveTo(-45,-1,-39,-18);ctx.stroke();ctx.fillStyle='#a72b34';ctx.beginPath();ctx.moveTo(-6,14);ctx.lineTo(1,22);ctx.lineTo(7,13);ctx.closePath();ctx.fill();ctx.restore()}
function drawLevel5Flora(){if(level!==5)return;const beds=[[28,42,1],[W-31,46,2],[34,H-42,3],[W-36,H-44,4]];beds.forEach(([x,y,seed])=>{for(let i=0;i<13;i++){const a=i*.77+seed*.2,r=15+(i%4)*9,lx=x+Math.cos(a)*r,ly=y+Math.sin(a)*r;ctx.fillStyle=i%3?'#315b3b':'#587847';ctx.beginPath();ctx.ellipse(lx,ly,18,7,a,0,7);ctx.fill()}const color=['#a970cf','#62b7c5','#efbd48','#d6657e'][seed-1];ctx.fillStyle=color;for(let petal=0;petal<6;petal++){const a=petal*Math.PI/3;ctx.beginPath();ctx.ellipse(x+Math.cos(a)*7,y+Math.sin(a)*7,7,3,a,0,7);ctx.fill()}ctx.fillStyle='#d8df89';ctx.beginPath();ctx.arc(x,y,3,0,7);ctx.fill()});const thornBeds=[[8,H*.34,1],[W-8,H*.58,-1],[10,H*.73,1],[W-10,H*.28,-1]];thornBeds.forEach(([x,y,side])=>{ctx.strokeStyle='#273f2c';ctx.lineWidth=5;for(let i=0;i<7;i++){const py=y-35+i*12,len=23+(i%3)*8;ctx.beginPath();ctx.moveTo(x,py);ctx.lineTo(x+side*len,py-8);ctx.stroke();ctx.fillStyle='#66784a';ctx.beginPath();ctx.ellipse(x+side*len,py-8,11,5,-side*.35,0,7);ctx.fill();ctx.fillStyle='#b7c77a';ctx.beginPath();ctx.moveTo(x+side*len*.55,py-4);ctx.lineTo(x+side*(len*.55+9),py-13);ctx.lineTo(x+side*(len*.55+5),py-1);ctx.closePath();ctx.fill()}})}
function drawQuicksand(){quicksand.forEach((p,index)=>{const x=(p.x+.5)*CELL,y=(p.y+.5)*CELL;ctx.save();ctx.fillStyle='rgba(48,39,25,.68)';puddlePath(p,x+2,y+4,1.08);ctx.fill();ctx.fillStyle=index%2?'#a1844d':'#947747';puddlePath(p,x,y,1);ctx.fill();ctx.strokeStyle='#c3a66c';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='rgba(61,47,28,.45)';ctx.lineWidth=2;for(let ring=.24;ring<.86;ring+=.2){puddlePath(p,x,y,ring);ctx.stroke()}ctx.fillStyle='rgba(225,196,124,.45)';for(let i=0;i<7;i++){const a=i*2.3+p.seed,r=(i%3+1)*7;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,2+(i%2),0,7);ctx.fill()}ctx.restore()})}
function puddlePoint(p,step,total,scale=1){const a=step/total*Math.PI*2,ruffle=1+Math.sin(a*p.lobes+p.seed)*.12+Math.sin(a*3-p.seed*.7)*.07,px=Math.cos(a)*p.rx*CELL*ruffle*scale,py=Math.sin(a)*p.ry*CELL*ruffle*scale,c=Math.cos(p.angle),s=Math.sin(p.angle);return{x:px*c-py*s,y:px*s+py*c}}
function puddlePath(p,x,y,scale=1){const points=18,first=puddlePoint(p,0,points,scale);ctx.beginPath();ctx.moveTo(x+first.x,y+first.y);for(let i=1;i<=points;i++){const current=puddlePoint(p,i%points,points,scale),previous=puddlePoint(p,(i-1)%points,points,scale),mid={x:(previous.x+current.x)/2,y:(previous.y+current.y)/2};ctx.quadraticCurveTo(x+previous.x,y+previous.y,x+mid.x,y+mid.y)}ctx.closePath()}
function drawLily(p,x,y,index){const count=p.lilies||0,scale=p.padScale||1;for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2+p.seed*.73,radius=(.18+(i%3)*.12),localX=Math.cos(a)*p.rx*CELL*radius,localY=Math.sin(a)*p.ry*CELL*radius,c=Math.cos(p.angle),s=Math.sin(p.angle),lx=x+localX*c-localY*s,ly=y+localX*s+localY*c,size=(7+(i+p.seed)%4)*scale,notch=a+.7;ctx.fillStyle=i%3===0?'#789e45':i%3===1?'#557d3c':'#6c9143';ctx.beginPath();ctx.arc(lx,ly,size,notch+.25,notch+Math.PI*2-.25);ctx.lineTo(lx,ly);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(35,68,39,.65)';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.moveTo(lx,ly);ctx.lineTo(lx+Math.cos(notch)*size*.78,ly+Math.sin(notch)*size*.78);ctx.stroke();if((i+p.seed)%3===0){const flowerColor=(i+p.seed)%2?'#eee0b1':'#d9b9d8';ctx.fillStyle=flowerColor;for(let petal=0;petal<6;petal++){const pa=petal*Math.PI/3;ctx.beginPath();ctx.ellipse(lx+Math.cos(pa)*4,ly+Math.sin(pa)*4,4.5,2.2,pa,0,7);ctx.fill()}ctx.fillStyle='#d8a941';ctx.beginPath();ctx.arc(lx,ly,2,0,7);ctx.fill()}}}
function drawPuddles(){puddles.forEach((p,index)=>{const x=(p.x+.5)*CELL,y=(p.y+.5)*CELL;ctx.save();ctx.fillStyle='rgba(31,48,40,.72)';puddlePath(p,x+2,y+4,1.08);ctx.fill();ctx.fillStyle=index%2?'rgba(43,118,132,.68)':'rgba(51,132,143,.64)';puddlePath(p,x,y,1);ctx.fill();ctx.strokeStyle='rgba(137,205,199,.68)';ctx.lineWidth=2;ctx.stroke();const sheen=ctx.createRadialGradient(x-p.rx*CELL*.25,y-p.ry*CELL*.25,2,x,y,Math.max(p.rx,p.ry)*CELL);sheen.addColorStop(0,'rgba(190,230,210,.2)');sheen.addColorStop(1,'rgba(17,76,91,.08)');ctx.fillStyle=sheen;puddlePath(p,x,y,.94);ctx.fill();ctx.strokeStyle='rgba(205,235,213,.24)';ctx.lineWidth=1;for(let ring=.38;ring<.82;ring+=.2){puddlePath(p,x,y,ring);ctx.stroke()}drawLily(p,x,y,index);ctx.restore()})}
function drawCanopyBase(){canopies.forEach(tree=>{const x=tree.x*CELL,y=tree.y*CELL;ctx.fillStyle='rgba(8,14,10,.28)';ctx.beginPath();ctx.ellipse(x+18,y+26,tree.r*.8,tree.r*.3,-.35,0,7);ctx.fill();ctx.strokeStyle=tree.type==='cedar'?'#58523d':'#4a4934';ctx.lineWidth=tree.type==='fern'?6:13;ctx.beginPath();ctx.moveTo(x,y+30);ctx.lineTo(x+8,y-6);ctx.stroke();if(tree.type!=='fern'){ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+4,y+6);ctx.lineTo(x-28,y-28);ctx.moveTo(x+3,y+3);ctx.lineTo(x+35,y-24);ctx.stroke()}})}
function drawCanopyTop(){canopies.forEach((tree,index)=>{const x=tree.x*CELL,y=tree.y*CELL;ctx.save();ctx.globalAlpha=.64;ctx.shadowColor='rgba(0,0,0,.3)';ctx.shadowBlur=13;if(tree.type==='palm'||tree.type==='fern'){for(let i=0;i<(tree.type==='palm'?11:15);i++){const a=i*(Math.PI*2/(tree.type==='palm'?11:15)),len=tree.r*(tree.type==='palm'?1:.7);ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle=i%2?'#315c3a':'#4b7448';ctx.beginPath();ctx.ellipse(len*.38,0,len*.48,tree.type==='palm'?9:5,0,0,7);ctx.fill();ctx.restore()}}else if(tree.type==='cedar'){for(let i=0;i<7;i++){ctx.fillStyle=i%2?'#244a37':'#365e42';ctx.beginPath();ctx.moveTo(x,y-tree.r*.8+i*12);ctx.lineTo(x-tree.r*.65+i*2,y+tree.r*.55);ctx.lineTo(x+tree.r*.65-i*2,y+tree.r*.55);ctx.closePath();ctx.fill()}}else{for(let i=0;i<10;i++){const a=i*2.2,n=tileNoise(i,index+3),r=tree.r*(.26+n*.2);ctx.fillStyle=i%3?'#294c31':'#3d653d';ctx.beginPath();ctx.arc(x+Math.cos(a)*tree.r*.38,y+Math.sin(a)*tree.r*.3,r,0,7);ctx.fill()}}ctx.globalAlpha=.2;ctx.fillStyle='#afc67b';ctx.beginPath();ctx.arc(x-tree.r*.16,y-tree.r*.18,tree.r*.35,0,7);ctx.fill();ctx.restore()})}
function drawHazard(h){
  const x=h.x*CELL+CELL/2,y=h.y*CELL+CELL/2;ctx.save();ctx.translate(x,y);ctx.strokeStyle='#151c17';ctx.lineWidth=2;
  if(h.type==='pillar'){ctx.fillStyle='#858c81';ctx.fillRect(-12,-15,24,30);ctx.strokeRect(-12,-15,24,30);ctx.fillStyle='#a1a69a';ctx.fillRect(-16,-15,32,7);ctx.fillStyle='#52614f';ctx.fillRect(-8,3,5,12)}
  if(h.type==='wall'){ctx.fillStyle='#747d73';ctx.fillRect(-17,-11,34,22);ctx.strokeRect(-17,-11,34,22);ctx.beginPath();ctx.moveTo(-2,-11);ctx.lineTo(5,0);ctx.lineTo(0,11);ctx.stroke()}
  if(h.type==='rock'){const seed=h.x*19+h.y*31,lean=(seed%7)-3;ctx.rotate(((seed%9)-4)*.025);ctx.shadowColor='rgba(8,13,10,.38)';ctx.shadowBlur=5;ctx.shadowOffsetY=4;ctx.fillStyle='#56615a';ctx.beginPath();ctx.moveTo(-17+lean*.3,8);ctx.quadraticCurveTo(-18,-3,-10,-12);ctx.quadraticCurveTo(-3,-18,7,-14);ctx.quadraticCurveTo(17,-10,17,1);ctx.quadraticCurveTo(18,11,7,15);ctx.quadraticCurveTo(-6,18,-17,8);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowColor='transparent';const face=ctx.createLinearGradient(-10,-14,12,15);face.addColorStop(0,'#a2aaa0');face.addColorStop(.42,'#7c877e');face.addColorStop(1,'#4a554e');ctx.fillStyle=face;ctx.beginPath();ctx.moveTo(-11,-8);ctx.quadraticCurveTo(-2,-16,8,-11);ctx.lineTo(13,-2);ctx.lineTo(4,5);ctx.lineTo(-9,3);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(44,54,47,.75)';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(4,5);ctx.lineTo(8,14);ctx.moveTo(-9,3);ctx.lineTo(-15,9);ctx.moveTo(3,-10);ctx.lineTo(-1,-3);ctx.lineTo(5,1);ctx.stroke();ctx.fillStyle='rgba(111,139,79,.68)';ctx.beginPath();ctx.arc(-8,-7,4,0,7);ctx.arc(-4,-9,3,0,7);ctx.arc(-11,-3,2.5,0,7);ctx.fill();ctx.fillStyle='rgba(222,229,210,.34)';ctx.beginPath();ctx.ellipse(3,-10,5,2,-.25,0,7);ctx.fill()}
  if(h.type==='thorns'){ctx.fillStyle='#8c442e';for(let i=0;i<5;i++){ctx.save();ctx.rotate(i*1.25);ctx.beginPath();ctx.moveTo(-4,0);ctx.lineTo(0,-18);ctx.lineTo(5,0);ctx.fill();ctx.restore()}}
  ctx.restore();
}
function drawMouse(){
  if(mouse.type==='boss'){const x=(mouse.x+.5)*CELL,y=(mouse.y+.5)*CELL;drawBossFigure(x,y,1.35);if(state==='bossDefeated')drawBossDefeat(x,y);return}
  const x=(mouse.x+.5)*CELL,y=(mouse.y+.5)*CELL,jumper=mouse.type==='jumper',water=mouse.type==='water',spikeMouse=mouse.type==='spike',boss=mouse.type==='boss',body=boss?'#43543a':spikeMouse?'#744f86':water?'#62aaa9':jumper?'#7fa5a2':'#cbbbaa',bob=Math.sin(performance.now()/180)*2-Math.sin(mouse.jump*Math.PI)*(water?10:22);mouse.jump=Math.max(0,mouse.jump-.045);ctx.save();ctx.translate(x,y+bob);if(boss)ctx.scale(1.9,1.9);if(water){ctx.strokeStyle='rgba(111,205,211,.7)';ctx.beginPath();ctx.ellipse(0,12,20,6,0,0,7);ctx.stroke()}if(spikeMouse&&mouse.armed){ctx.fillStyle='#f2e7c9';ctx.strokeStyle='#392c43';for(let i=0;i<9;i++){const a=i*Math.PI*2/9;ctx.save();ctx.rotate(a);ctx.beginPath();ctx.moveTo(2,-3);ctx.lineTo(21,0);ctx.lineTo(2,3);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}}ctx.fillStyle=body;ctx.beginPath();ctx.ellipse(0,2,jumper||water||spikeMouse||boss?12:11,jumper||water||boss?9:8,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(8,-3,jumper||water||spikeMouse||boss?6.5:6,0,7);ctx.fill();ctx.fillStyle=boss?'#71805b':spikeMouse?'#c79fce':water?'#a3ded5':jumper?'#d28b66':'#d99387';ctx.beginPath();ctx.arc(5,-8,jumper||water||spikeMouse||boss?4:3,0,7);ctx.arc(11,-7,jumper||water||spikeMouse||boss?4:3,0,7);ctx.fill();if(jumper){ctx.strokeStyle='#344f54';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-6,-5);ctx.lineTo(-4,8);ctx.moveTo(1,-6);ctx.lineTo(3,9);ctx.stroke()}if(water){ctx.fillStyle='#dbe695';ctx.beginPath();ctx.arc(-2,2,4,0,7);ctx.fill()}if(jumper||water||spikeMouse||boss){ctx.fillStyle=boss?'#2d3828':spikeMouse?'#4b3357':'#d7c068';ctx.beginPath();ctx.ellipse(-7,9,6,3,-.2,0,7);ctx.fill()}if(boss){ctx.fillStyle='#78944b';for(let i=0;i<5;i++){ctx.save();ctx.rotate(-.8+i*.35);ctx.beginPath();ctx.ellipse(4,-12,8,3,0,0,7);ctx.fill();ctx.restore()}}ctx.fillStyle='#141a16';ctx.beginPath();ctx.arc(10,-4,1.5,0,7);ctx.fill();ctx.strokeStyle=body;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-9,3);ctx.quadraticCurveTo(-20,-6,-16,-13);ctx.stroke();if(spikeMouse&&!mouse.armed){ctx.fillStyle='#f2e7c9';ctx.font='bold 8px Courier New';ctx.textAlign='center';ctx.fillText('SAFE',0,23)}ctx.restore();
}
function drawExtraMouse(){if(!extraMouse)return;const active=mouse;mouse=extraMouse;drawMouse();mouse=active}
function drawSpikes(){spikes.forEach(spike=>{const x=(spike.x-spike.dy*spike.lane+.5)*CELL,y=(spike.y+spike.dx*spike.lane+.5)*CELL,a=Math.atan2(spike.dy,spike.dx);ctx.save();ctx.translate(x,y);if(spike.kind==='spit'||spike.kind==='bossSpit'){const pulse=1+Math.sin(performance.now()/70)*.16;ctx.rotate(a);ctx.scale(pulse,pulse);ctx.shadowColor='#8fe84d';ctx.shadowBlur=18;ctx.fillStyle='#071009';ctx.strokeStyle='#79c842';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<12;i++){const pa=i*Math.PI/6,r=i%2?10:13;ctx.lineTo(Math.cos(pa)*r,Math.sin(pa)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#a6ef61';ctx.beginPath();ctx.arc(3,-3,3,0,7);ctx.fill();ctx.fillStyle='rgba(75,151,50,.75)';ctx.beginPath();ctx.arc(-17,0,6,0,7);ctx.arc(-27,2,3,0,7);ctx.fill()}else{ctx.rotate(a);ctx.fillStyle='#f2e7c9';ctx.strokeStyle='#4b3357';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-10,-5);ctx.lineTo(-6,0);ctx.lineTo(-10,5);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()})}
function drawRelic(){if(!relic)return;const x=(relic.x+.5)*CELL,y=(relic.y+.5)*CELL,pulse=1+Math.sin(performance.now()/130)*.12;ctx.save();ctx.translate(x,y);ctx.scale(pulse,pulse);ctx.shadowColor='#e0af43';ctx.shadowBlur=12;ctx.fillStyle='#e0af43';ctx.beginPath();ctx.ellipse(0,0,8,12,0,0,7);ctx.fill();ctx.strokeStyle='#292016';ctx.beginPath();ctx.moveTo(-7,-2);ctx.lineTo(7,-2);ctx.moveTo(-7,4);ctx.lineTo(7,4);ctx.stroke();ctx.restore()}
function drawResistanceFruit(){if(!resistanceFruit)return;const now=performance.now(),x=(resistanceFruit.x+.5)*CELL,y=(resistanceFruit.y+.5)*CELL-riseEffect(now-resistanceFruit.riseAt),pulse=1+Math.sin(now/110)*.1;ctx.save();ctx.translate(x,y);ctx.strokeStyle=`rgba(199,255,229,${.5+Math.sin(now/130)*.2})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,24+Math.sin(now/120)*3,0,7);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4+now/900;ctx.beginPath();ctx.moveTo(Math.cos(a)*28,Math.sin(a)*28);ctx.lineTo(Math.cos(a)*36,Math.sin(a)*36);ctx.stroke()}ctx.scale(pulse,pulse);ctx.shadowColor='#8ff4de';ctx.shadowBlur=22;ctx.fillStyle='rgba(95,204,198,.58)';ctx.beginPath();ctx.ellipse(0,13,22,7,0,0,7);ctx.fill();ctx.fillStyle='#56c7ad';ctx.strokeStyle='#174f48';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-15);ctx.bezierCurveTo(17,-13,17,9,0,17);ctx.bezierCurveTo(-17,9,-17,-13,0,-15);ctx.fill();ctx.stroke();ctx.fillStyle='#d8f49b';ctx.beginPath();ctx.ellipse(7,-17,11,5,-.55,0,7);ctx.fill();ctx.fillStyle='#efffd1';ctx.beginPath();ctx.arc(-4,-4,4,0,7);ctx.fill();ctx.restore()}
function riseEffect(age){return Math.max(0,18-Math.min(18,age/45))}
function drawBossDefeat(x,y){const now=performance.now(),orbit=(now-bossDefeatStarted)/170;ctx.save();ctx.strokeStyle='#d7b441';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x-12,y-10,7,0,Math.PI);ctx.arc(x+13,y-10,7,0,Math.PI);ctx.stroke();for(let i=0;i<5;i++){const a=orbit+i*Math.PI*2/5,ox=x+Math.cos(a)*42,oy=y-34+Math.sin(a)*13;ctx.save();ctx.translate(ox,oy);ctx.rotate(-a*.4);if(i%2===0){ctx.fillStyle='#f2c84f';ctx.strokeStyle='#7b5923';ctx.beginPath();ctx.moveTo(-8,-6);ctx.lineTo(10,-4);ctx.lineTo(8,8);ctx.lineTo(-10,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#9b7129';ctx.beginPath();ctx.arc(-3,0,2,0,7);ctx.arc(5,3,1.5,0,7);ctx.fill()}else{ctx.fillStyle=i===1?'#79b6c8':'#d47c5b';ctx.beginPath();ctx.ellipse(0,1,8,5,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(6,-3,4,0,7);ctx.fill();ctx.fillStyle='#f0c25b';ctx.beginPath();ctx.moveTo(10,-3);ctx.lineTo(16,0);ctx.lineTo(10,2);ctx.fill();ctx.strokeStyle='#29382f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-3,4);ctx.lineTo(-7,9);ctx.stroke()}ctx.restore()}ctx.restore()}
function drawSnake(){
  const skin=skins[skinName];
  const motion=performance.now(),dying=state==='dying',happy=state==='bossDefeated',hurt=motion<hurtUntil,eating=motion<mouthUntil;ctx.save();if(dying)ctx.translate(Math.sin(motion/55)*3,Math.cos(motion/70)*2);if(happy)ctx.translate(0,-Math.abs(Math.sin((motion-bossDefeatStarted)/150))*8);
  ctx.lineCap='round';
  for(let i=snake.length-1;i>0;i--){const a=snake[i],b=snake[i-1];ctx.strokeStyle='#18251c';ctx.lineWidth=15;ctx.beginPath();ctx.moveTo((a.x+.5)*CELL,(a.y+.5)*CELL);ctx.lineTo((b.x+.5)*CELL,(b.y+.5)*CELL);ctx.stroke();ctx.strokeStyle=skin.link;ctx.lineWidth=8;ctx.stroke()}
  for(let i=snake.length-1;i>=0;i--){
    const s=snake[i],near=snake[Math.max(0,i-1)];let x=(s.x+.5)*CELL,y=(s.y+.5)*CELL;const t=i/Math.max(1,snake.length-1),wide=i===0?18:Math.max(10,16-t*5),long=i===0?21:17;
    const angle=i===0?Math.atan2(directions[dir].y,directions[dir].x):Math.atan2(near.y-s.y,near.x-s.x);
    ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.shadowColor='rgba(0,0,0,.45)';ctx.shadowBlur=5;ctx.shadowOffsetY=4;
    const shell=ctx.createLinearGradient(0,-wide,0,wide);shell.addColorStop(0,skin.top);shell.addColorStop(.45,i%2?skin.mid:skin.top);shell.addColorStop(1,skin.low);ctx.fillStyle=shell;ctx.strokeStyle='#17251b';ctx.lineWidth=2.5;ctx.beginPath();if(skin.shape==='diamond'&&i>0){ctx.moveTo(-long,0);ctx.lineTo(-long*.35,-wide);ctx.lineTo(long*.45,-wide*.75);ctx.lineTo(long,0);ctx.lineTo(long*.35,wide);ctx.lineTo(-long*.45,wide*.75);ctx.closePath()}else if(skin.shape==='armor'&&i>0){const r=4;ctx.moveTo(-long+r,-wide);ctx.lineTo(long-r,-wide);ctx.quadraticCurveTo(long,-wide,long,-wide+r);ctx.lineTo(long,wide-r);ctx.quadraticCurveTo(long,wide,long-r,wide);ctx.lineTo(-long+r,wide);ctx.quadraticCurveTo(-long,wide,-long,wide-r);ctx.lineTo(-long,-wide+r);ctx.quadraticCurveTo(-long,-wide,-long+r,-wide);ctx.closePath()}else ctx.ellipse(0,0,long,wide,0,0,7);ctx.fill();ctx.stroke();
    ctx.shadowColor='transparent';ctx.strokeStyle='rgba(218,239,159,.32)';ctx.lineWidth=1;for(let band=-12;band<=12;band+=5){const height=wide*Math.sqrt(Math.max(0,1-band*band/(long*long)));ctx.beginPath();ctx.moveTo(band,-height+3);ctx.lineTo(band,height-3);ctx.stroke()}
    if(skinName==='viper'&&i%2){ctx.fillStyle='rgba(47,26,22,.7)';ctx.beginPath();ctx.moveTo(-5,-wide+2);ctx.lineTo(5,0);ctx.lineTo(-5,wide-2);ctx.closePath();ctx.fill()}if(skinName==='boa'&&i>0){ctx.strokeStyle='rgba(230,244,238,.7)';ctx.strokeRect(-long+4,-wide+4,long*2-8,wide*2-8)}
    if(i>0){ctx.fillStyle='#263d2b';ctx.beginPath();ctx.arc(0,0,4.2,0,7);ctx.fill();ctx.strokeStyle=skin.joint;ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(0,0,2.2,0,7);ctx.stroke()}
    ctx.restore();
  }
  const h=snake[0],x=(h.x+.5)*CELL,y=(h.y+.5)*CELL,d=directions[dir],side={x:-d.y,y:d.x};ctx.fillStyle='#101812';for(const sign of[-1,1]){const ex=x+d.x*6+side.x*sign*6,ey=y+d.y*6+side.y*sign*6;if(hurt||dying){ctx.strokeStyle='#2a1713';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(ex-3,ey-3);ctx.lineTo(ex+3,ey+3);ctx.moveTo(ex+3,ey-3);ctx.lineTo(ex-3,ey+3);ctx.stroke()}else{ctx.beginPath();ctx.arc(ex,ey,2.5,0,7);ctx.fill();ctx.fillStyle='#dceaa8';ctx.beginPath();ctx.arc(ex-.7,ey-.7,.7,0,7);ctx.fill();ctx.fillStyle='#101812'}}if(eating){ctx.fillStyle='#301713';ctx.strokeStyle='#e2a080';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+d.x*10+side.x*12,y+d.y*10+side.y*12);ctx.quadraticCurveTo(x+d.x*32,y+d.y*32,x+d.x*10-side.x*12,y+d.y*10-side.y*12);ctx.quadraticCurveTo(x+d.x*14,y+d.y*14,x+d.x*10+side.x*12,y+d.y*10+side.y*12);ctx.fill();ctx.stroke()}else{ctx.strokeStyle=hurt?'#52271f':'#d35b4b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+d.x*15,y+d.y*15);ctx.lineTo(x+d.x*(hurt?18:22)+side.x*(hurt?4:0),y+d.y*(hurt?18:22)+side.y*(hurt?4:0));ctx.stroke()}if(dying){const orbit=(motion-deathStarted)/130;for(let i=0;i<4;i++){const a=orbit+i*Math.PI/2,sx=x+Math.cos(a)*28,sy=y-24+Math.sin(a)*10;ctx.save();ctx.translate(sx,sy);ctx.rotate(-orbit+i);ctx.fillStyle=i%2?'#f3d15d':'#fff0a0';ctx.strokeStyle='#6d5420';ctx.lineWidth=1;ctx.beginPath();for(let point=0;point<10;point++){const radius=point%2?4:9,pa=-Math.PI/2+point*Math.PI/5;ctx.lineTo(Math.cos(pa)*radius,Math.sin(pa)*radius)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}}
  if(happy){for(let i=0;i<3;i++){const a=(motion-bossDefeatStarted)/240+i*2.1,hx=x+Math.cos(a)*34,hy=y-26-Math.abs(Math.sin(a))*15;ctx.save();ctx.translate(hx,hy);ctx.rotate(Math.sin(a)*.25);ctx.fillStyle=i%2?'#f0ce54':'#e8756d';ctx.beginPath();ctx.arc(-3,-2,4,0,7);ctx.arc(3,-2,4,0,7);ctx.lineTo(0,7);ctx.closePath();ctx.fill();ctx.restore()}}
  ctx.restore();
}
function drawParticles(dt){particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x-3,p.y-3,6,6)});ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0)}
function frame(now){if(state==='running'&&now-lastWorldStep>=MOVE_TICKS.python){lastWorldStep=now;updateLevel5MouseSpawn();updateBossGuard();if(mouse&&mouse.type==='boss')updateBoss(snake[0]);updateSpikes()}const quicksandSlow=(level===4||level===5)&&now<quicksandUntil?2:1,tick=MOVE_TICKS[skinName]*quicksandSlow;if(state==='running'&&now-lastStep>=tick){lastStep=now;step()}drawFloor();drawQuicksand();drawPuddles();drawLevel5Flora();drawTemple();drawBossCactus();drawCanopyBase();hazards.forEach(drawHazard);drawRelic();if(mouse)drawMouse();drawExtraMouse();drawBossGuard();drawSpikes();drawSnake();drawParticles(Math.min(.03,(now-(frame.last||now))/1000));drawCanopyTop();drawResistanceFruit();frame.last=now;if(flash>0){ctx.fillStyle=`rgba(163,77,50,${flash*.35})`;ctx.fillRect(0,0,W,H);flash-=.08}requestAnimationFrame(frame)}
const launchParams=new URLSearchParams(location.search),rawLevel=Number(launchParams.get('level')),requestedLevel=[1,2,3,4,5].includes(rawLevel)?rawLevel:1;loadProgress();chooseSkin(launchParams.get('snake')||'python');resetGame(true,requestedLevel);requestAnimationFrame(frame);
